#define HAVE_ACCEPT4
#define HAVE_ADJTIME
#define HAVE_ADJTIMEX
#define HAVE_AIO_H
#define HAVE_ALIGNED_128
#define HAVE_ALIGNED_64
#define HAVE_ALIGNED_64K
#define HAVE_ALIGNED_ALLOC
#define HAVE_ARCH_PRCTL
#define HAVE_ASM_LDT_H
#define HAVE_ASM_MB
#define HAVE_ASM_MTRR_H
#define HAVE_ASM_NOP
#define HAVE_ASM_NOTHING
#define HAVE_ASM_PRCTL_H
#define HAVE_ASM_X86_CLDEMOTE
#define HAVE_ASM_X86_CLFLUSH
#define HAVE_ASM_X86_CLFLUSHOPT
#define HAVE_ASM_X86_CLTS
#define HAVE_ASM_X86_CLWB
#define HAVE_ASM_X86_HLT
#define HAVE_ASM_X86_INVD
#define HAVE_ASM_X86_INVLPG
#define HAVE_ASM_X86_LFENCE
#define HAVE_ASM_X86_LGDT
#define HAVE_ASM_X86_LLDT
#define HAVE_ASM_X86_LMSW
#define HAVE_ASM_X86_MFENCE
#define HAVE_ASM_X86_MOV_CR0
#define HAVE_ASM_X86_MOV_DR0
#define HAVE_ASM_X86_PAUSE
#define HAVE_ASM_X86_PREFETCHNTA
#define HAVE_ASM_X86_PREFETCHT0
#define HAVE_ASM_X86_PREFETCHT1
#define HAVE_ASM_X86_PREFETCHT2
#define HAVE_ASM_X86_RDMSR
#define HAVE_ASM_X86_RDPMC
#define HAVE_ASM_X86_RDRAND
#define HAVE_ASM_X86_RDSEED
#define HAVE_ASM_X86_RDTSC
#define HAVE_ASM_X86_RDTSCP
#define HAVE_ASM_X86_REP_STOSB
#define HAVE_ASM_X86_REP_STOSD
#define HAVE_ASM_X86_REP_STOSQ
#define HAVE_ASM_X86_REP_STOSW
#define HAVE_ASM_X86_SERIALIZE
#define HAVE_ASM_X86_SFENCE
#define HAVE_ASM_X86_TPAUSE
#define HAVE_ASM_X86_WRINVD
#define HAVE_ASM_X86_WRMSR
#define HAVE_ATOMIC
#define HAVE_ATOMIC_ADD_FETCH
#define HAVE_ATOMIC_AND_FETCH
#define HAVE_ATOMIC_CLEAR
#define HAVE_ATOMIC_COMPARE_EXCHANGE
#define HAVE_ATOMIC_FETCH_ADD
#define HAVE_ATOMIC_FETCH_ADD_2
#define HAVE_ATOMIC_FETCH_ADD_4
#define HAVE_ATOMIC_FETCH_ADD_8
#define HAVE_ATOMIC_FETCH_AND
#define HAVE_ATOMIC_FETCH_NAND
#define HAVE_ATOMIC_FETCH_OR
#define HAVE_ATOMIC_FETCH_SUB
#define HAVE_ATOMIC_FETCH_XOR
#define HAVE_ATOMIC_LOAD
#define HAVE_ATOMIC_LOAD_DOUBLE
#define HAVE_ATOMIC_NAND_FETCH
#define HAVE_ATOMIC_OR_FETCH
#define HAVE_ATOMIC_STORE
#define HAVE_ATOMIC_STORE_DOUBLE
#define HAVE_ATOMIC_SUB_FETCH
#define HAVE_ATOMIC_TEST_AND_SET
#define HAVE_ATOMIC_XOR_FETCH
#define HAVE_ATTRIBUTE_ALWAYS_INLINE
#define HAVE_ATTRIBUTE_FAST_MATH
#define HAVE_ATTRIBUTE_HOT
#define HAVE_ATTRIBUTE_NOINLINE
#define HAVE_ATTRIBUTE_NORETURN
#define HAVE_ATTRIBUTE_PURE
#define HAVE_ATTRIBUTE_WARN_UNUSED_RESULT
#define HAVE_ATTRIBUTE_WEAK
#define HAVE_BRK
#define HAVE_BSEARCH
#define HAVE_BUILTIN_ASSUME_ALIGNED
#define HAVE_BUILTIN_BSWAP32
#define HAVE_BUILTIN_CABSL
#define HAVE_BUILTIN_CCOS
#define HAVE_BUILTIN_CCOSF
#define HAVE_BUILTIN_CCOSL
#define HAVE_BUILTIN_CEXP
#define HAVE_BUILTIN_CLZ
#define HAVE_BUILTIN_CLZL
#define HAVE_BUILTIN_CLZLL
#define HAVE_BUILTIN_CONSTANT_P
#define HAVE_BUILTIN_COS
#define HAVE_BUILTIN_COSF
#define HAVE_BUILTIN_COSHL
#define HAVE_BUILTIN_COSL
#define HAVE_BUILTIN_CPOW
#define HAVE_BUILTIN_CSIN
#define HAVE_BUILTIN_CSINF
#define HAVE_BUILTIN_CSINL
#define HAVE_BUILTIN_CTZ
#define HAVE_BUILTIN_EXP
#define HAVE_BUILTIN_EXPECT
#define HAVE_BUILTIN_EXPL
#define HAVE_BUILTIN_FABS
#define HAVE_BUILTIN_FABSF
#define HAVE_BUILTIN_FABSL
#define HAVE_BUILTIN_IA32_MOVNTDQ
#define HAVE_BUILTIN_IA32_MOVNTI
#define HAVE_BUILTIN_IA32_MOVNTI64
#define HAVE_BUILTIN_LGAMMAL
#define HAVE_BUILTIN_LLABS
#define HAVE_BUILTIN_LOG
#define HAVE_BUILTIN_LOGL
#define HAVE_BUILTIN_MEMCMP
#define HAVE_BUILTIN_MEMCPY
#define HAVE_BUILTIN_MEMMOVE
#define HAVE_BUILTIN_MEMSET
#define HAVE_BUILTIN_PARITY
#define HAVE_BUILTIN_POPCOUNT
#define HAVE_BUILTIN_POPCOUNTL
#define HAVE_BUILTIN_POPCOUNTLL
#define HAVE_BUILTIN_POW
#define HAVE_BUILTIN_PREFETCH
#define HAVE_BUILTIN_RINT
#define HAVE_BUILTIN_RINTL
#define HAVE_BUILTIN_ROUNDL
#define HAVE_BUILTIN_SFENCE
#define HAVE_BUILTIN_SHUFFLE
#define HAVE_BUILTIN_SIN
#define HAVE_BUILTIN_SINCOS
#define HAVE_BUILTIN_SINCOSF
#define HAVE_BUILTIN_SINCOSL
#define HAVE_BUILTIN_SINF
#define HAVE_BUILTIN_SINHL
#define HAVE_BUILTIN_SINL
#define HAVE_BUILTIN_SQRT
#define HAVE_BUILTIN_SQRTL
#define HAVE_BUILTIN_SUPPORTS
#define HAVE_BUILTIN_TAN
#define HAVE_BUILTIN_TANF
#define HAVE_BUILTIN_TANL
#define HAVE_BUILTIN___CLEAR_CACHE
#define HAVE_CABSL
#define HAVE_CCOS
#define HAVE_CCOSF
#define HAVE_CCOSL
#define HAVE_CDROM_BLK
#define HAVE_CDROM_MCN
#define HAVE_CDROM_MSF
#define HAVE_CDROM_READ_AUDIO
#define HAVE_CDROM_SUBCHNL
#define HAVE_CDROM_TI
#define HAVE_CDROM_TOCENTRY
#define HAVE_CDROM_TOCHDR
#define HAVE_CDROM_VOLCTRL
#define HAVE_CFGETISPEED
#define HAVE_CFGETOSPEED
#define HAVE_CHROOT
#define HAVE_CIMAG
#define HAVE_CIMAGF
#define HAVE_CIMAGL
#define HAVE_CLEARENV
#define HAVE_CLOCK_ADJTIME
#define HAVE_CLOCK_GETRES
#define HAVE_CLOCK_GETTIME
#define HAVE_CLOCK_NANOSLEEP
#define HAVE_CLOCK_SETTIME
#define HAVE_CLONE
#define HAVE_COMPLEX
#define HAVE_COMPLEX_H
#define HAVE_CONSOLEFONTDESC
#define HAVE_COPY_FILE_RANGE
#define HAVE_COSHL
#define HAVE_COSL
#define HAVE_CPOW
#define HAVE_CREAL
#define HAVE_CREALF
#define HAVE_CREALL
#define HAVE_CRYPT_H
#define HAVE_CRYPT_R
#define HAVE_CSIN
#define HAVE_CSINF
#define HAVE_CSINL
#define HAVE_DADDR_T
#define HAVE_DM_IOCTL
#define HAVE_DRAND48
#define HAVE_DVD_AUTHINFO
#define HAVE_DVD_STRUCT
#define HAVE_Decimal128
#define HAVE_Decimal32
#define HAVE_Decimal64
#define HAVE_ENDMNTENT
#define HAVE_ENDPWENT
#define HAVE_EPOLL_CREATE
#define HAVE_EPOLL_CREATE1
#define HAVE_EVENTFD
#define HAVE_EXECUTABLE_START
#define HAVE_EXECVEAT
#define HAVE_EXPL
#define HAVE_FACCESSAT
#define HAVE_FALLOCATE
#define HAVE_FANOTIFY
#define HAVE_FCHMODAT
#define HAVE_FCHOWNAT
#define HAVE_FDATASYNC
#define HAVE_FEATURES_H
#define HAVE_FENV_H
#define HAVE_FGETXATTR
#define HAVE_FLISTXATTR
#define HAVE_FLOAT_H
#define HAVE_FLOCK
#define HAVE_FLOPPY_DRIVE_STRUCT
#define HAVE_FLOPPY_FDC_STATE
#define HAVE_FLOPPY_STRUCT
#define HAVE_FLOPPY_WRITE_ERRORS
#define HAVE_FREMOVEXATTR
#define HAVE_FSETXATTR
#define HAVE_FSTAT
#define HAVE_FSTATAT
#define HAVE_FSVERITY_DIGEST
#define HAVE_FSVERITY_ENABLE_ARG
#define HAVE_FSXATTR_STRUCT
#define HAVE_FSYNC
#define HAVE_FUTIMENS
#define HAVE_FUTIMES
#define HAVE_FUTIMESAT
#define HAVE_Float128
#define HAVE_Float16
#define HAVE_Float32
#define HAVE_Float32x
#define HAVE_Float64
#define HAVE_Float64x
#define HAVE_GETAUXVAL
#define HAVE_GETCPU
#define HAVE_GETDOMAINNAME
#define HAVE_GETDTABLESIZE
#define HAVE_GETENTROPY
#define HAVE_GETHOSTID
#define HAVE_GETHOSTNAME
#define HAVE_GETITIMER
#define HAVE_GETLOADAVG
#define HAVE_GETMNTENT
#define HAVE_GETPAGESIZE
#define HAVE_GETPGID
#define HAVE_GETPGRP
#define HAVE_GETPRIORITY
#define HAVE_GETPWENT
#define HAVE_GETRANDOM
#define HAVE_GETRESGID
#define HAVE_GETRESUID
#define HAVE_GETRUSAGE
#define HAVE_GETSID
#define HAVE_GETTID
#define HAVE_GETTIMEOFDAY
#define HAVE_GETXATTR
#define HAVE_GMP_H
#define HAVE_GRP_H
#define HAVE_HSEARCH
#define HAVE_ICMPHDR
#define HAVE_IFADDRS_H
#define HAVE_IFCONF
#define HAVE_IFREQ
#define HAVE_IMMINTRIN_H
#define HAVE_INO64_T
#define HAVE_INOTIFY
#define HAVE_INOTIFY1
#define HAVE_INT128_T
#define HAVE_INTRINSIC_ROLB
#define HAVE_INTRINSIC_ROLD
#define HAVE_INTRINSIC_ROLQ
#define HAVE_INTRINSIC_ROLW
#define HAVE_INTRINSIC_RORB
#define HAVE_INTRINSIC_RORD
#define HAVE_INTRINSIC_RORQ
#define HAVE_INTRINSIC_RORW
#define HAVE_IOPL
#define HAVE_IOPORT
#define HAVE_IPHDR
#define HAVE_ITIMER_WHICH_T
#define HAVE_KBDIACRS
#define HAVE_KBENTRY
#define HAVE_KBKEYCODE
#define HAVE_KBSENTRY
#define HAVE_KERNEL_LONG_T
#define HAVE_KERNEL_ULONG_T
#define HAVE_KEY_T
#define HAVE_LABEL_AS_VALUE
#define HAVE_LANDLOCK_RULESET_ATTR
#define HAVE_LANDLOCK_RULE_TYPE
#define HAVE_LGAMMAL
#define HAVE_LGETXATTR
#define HAVE_LIBGEN_H
#define HAVE_LIBJPEG_H
#define HAVE_LIB_CRYPT
#define HAVE_LIB_DL
#define HAVE_LIB_JPEG
#define HAVE_LIB_PTHREAD
#define HAVE_LIB_PTHREAD_SPINLOCK
#define HAVE_LIB_RT
#define HAVE_LIB_Z
#define HAVE_LINKAT
#define HAVE_LINK_H
#define HAVE_LINUX_ANDROID_BINDERFS_H
#define HAVE_LINUX_ANDROID_BINDER_H
#define HAVE_LINUX_AUDIT_H
#define HAVE_LINUX_BLKZONED_H
#define HAVE_LINUX_CDROM_H
#define HAVE_LINUX_CN_PROC_H
#define HAVE_LINUX_CONNECTOR_H
#define HAVE_LINUX_DM_IOCTL_H
#define HAVE_LINUX_FD_H
#define HAVE_LINUX_FIEMAP_H
#define HAVE_LINUX_FILTER_H
#define HAVE_LINUX_FSVERITY_H
#define HAVE_LINUX_FS_H
#define HAVE_LINUX_FUTEX_H
#define HAVE_LINUX_GENETLINK_H
#define HAVE_LINUX_HDREG_H
#define HAVE_LINUX_HIDRAW_H
#define HAVE_LINUX_HPET_H
#define HAVE_LINUX_IF_ALG_H
#define HAVE_LINUX_IF_PACKET_H
#define HAVE_LINUX_IF_TUN_H
#define HAVE_LINUX_IO_URING_H
#define HAVE_LINUX_KD_H
#define HAVE_LINUX_KVM_H
#define HAVE_LINUX_LANDLOCK_H
#define HAVE_LINUX_LIRC_H
#define HAVE_LINUX_LOOP_H
#define HAVE_LINUX_MAGIC_H
#define HAVE_LINUX_MEDIA_H
#define HAVE_LINUX_MEMBARRIER_H
#define HAVE_LINUX_MEMPOLICY_H
#define HAVE_LINUX_MODULE_H
#define HAVE_LINUX_NETLINK_H
#define HAVE_LINUX_OPENAT2_H
#define HAVE_LINUX_PCI_H
#define HAVE_LINUX_PERF_EVENT_H
#define HAVE_LINUX_POSIX_TYPES_H
#define HAVE_LINUX_PPDEV_H
#define HAVE_LINUX_PTP_CLOCK_H
#define HAVE_LINUX_RANDOM_H
#define HAVE_LINUX_RSEQ_H
#define HAVE_LINUX_RTC_H
#define HAVE_LINUX_RTNETLINK_H
#define HAVE_LINUX_SECCOMP_H
#define HAVE_LINUX_SERIAL_H
#define HAVE_LINUX_SOCKET_H
#define HAVE_LINUX_SOCKIOS_H
#define HAVE_LINUX_SOCK_DIAG_H
#define HAVE_LINUX_SYSCTL_H
#define HAVE_LINUX_TASKSTATS_H
#define HAVE_LINUX_UDP_H
#define HAVE_LINUX_UNIX_DIAG_H
#define HAVE_LINUX_USBDEVICE_FS_H
#define HAVE_LINUX_USB_CDC_WDM_H
#define HAVE_LINUX_USERFAULTFD_H
#define HAVE_LINUX_VERSION_H
#define HAVE_LINUX_VIDEODEV2_H
#define HAVE_LINUX_VT_H
#define HAVE_LINUX_WATCHDOG_H
#define HAVE_LISTXATTR
#define HAVE_LLISTXATTR
#define HAVE_LOCALE_H
#define HAVE_LOCKF
#define HAVE_LOFF_T
#define HAVE_LOGL
#define HAVE_LOOKUP_DCOOKIE
#define HAVE_LRAND48
#define HAVE_LREMOVEXATTR
#define HAVE_LSEARCH
#define HAVE_LSEEK64
#define HAVE_LSETXATTR
#define HAVE_LSTAT
#define HAVE_MADVISE
#define HAVE_MALLOC_H
#define HAVE_MALLOC_TRIM
#define HAVE_MALLOPT
#define HAVE_MEDIA_DEVICE_INFO
#define HAVE_MEMALIGN
#define HAVE_MEMFD_CREATE
#define HAVE_MINCORE
#define HAVE_MKDIRAT
#define HAVE_MKNODAT
#define HAVE_MLOCK
#define HAVE_MLOCK2
#define HAVE_MLOCKALL
#define HAVE_MM256_ADD_EPI8
#define HAVE_MM256_DPBUSD_EPI32
#define HAVE_MM256_DPWSSD_EPI32
#define HAVE_MM256_LOADU_SI256
#define HAVE_MM256_STOREU_SI256
#define HAVE_MM512_ADD_EPI8
#define HAVE_MM512_DPBUSD_EPI32
#define HAVE_MM512_DPWSSD_EPI32
#define HAVE_MM512_LOADU_SI512
#define HAVE_MM512_STOREU_SI512
#define HAVE_MM_ADD_EPI8
#define HAVE_MM_DPBUSD_EPI32
#define HAVE_MM_DPWSSD_EPI32
#define HAVE_MM_LOADU_SI128
#define HAVE_MM_STOREU_SI128
#define HAVE_MNTENT_H
#define HAVE_MODE_T
#define HAVE_MODIFY_LDT
#define HAVE_MPROTECT
#define HAVE_MQUEUE_H
#define HAVE_MQ_POSIX
#define HAVE_MQ_SYSV
#define HAVE_MREMAP
#define HAVE_MSGINFO
#define HAVE_MSYNC
#define HAVE_MTRR_GENTRY
#define HAVE_MTRR_SENTRY
#define HAVE_MUNLOCK
#define HAVE_MUNLOCKALL
#define HAVE_NAME_TO_HANDLE_AT
#define HAVE_NANOSLEEP
#define HAVE_NETINET_IP_H
#define HAVE_NETINET_IP_ICMP_H
#define HAVE_NETINET_TCP_H
#define HAVE_NETINET_UDP_H
#define HAVE_NET_IF_H
#define HAVE_NICE
#define HAVE_OFF64_T
#define HAVE_OFF_T
#define HAVE_OPENAT
#define HAVE_OPENAT2
#define HAVE_OPEN_BY_HANDLE_AT
#define HAVE_OPEN_MEMSTREAM
#define HAVE_PERSONALITY
#define HAVE_PIDFD_GETFD
#define HAVE_PIDFD_OPEN
#define HAVE_PIDFD_SEND_SIGNAL
#define HAVE_PID_TYPE
#define HAVE_PIPE2
#define HAVE_PKEY_ALLOC
#define HAVE_PKEY_FREE
#define HAVE_PKEY_GET
#define HAVE_PKEY_MPROTECT
#define HAVE_PKEY_SET
#define HAVE_POLL_H
#define HAVE_POSIX_FADVISE
#define HAVE_POSIX_FALLOCATE
#define HAVE_POSIX_MADVISE
#define HAVE_POSIX_MEMALIGN
#define HAVE_POSIX_OPENPT
#define HAVE_POSIX_SPAWN
#define HAVE_POWL
#define HAVE_PPOLL
#define HAVE_PRAGMA
#define HAVE_PRAGMA_INSIDE
#define HAVE_PRCTL
#define HAVE_PREAD
#define HAVE_PREADV
#define HAVE_PREADV2
#define HAVE_PRIORITY_WHICH_T
#define HAVE_PRLIMIT
#define HAVE_PROCESS_VM_READV
#define HAVE_PROCESS_VM_WRITEV
#define HAVE_PSELECT
#define HAVE_PTHREAD_ATTR_SETSTACK
#define HAVE_PTHREAD_MUTEXATTR_DESTROY
#define HAVE_PTHREAD_MUTEXATTR_INIT
#define HAVE_PTHREAD_MUTEXATTR_SETPRIOCEILING
#define HAVE_PTHREAD_MUTEXATTR_SETPROTOCOL
#define HAVE_PTHREAD_MUTEXATTR_T
#define HAVE_PTHREAD_MUTEX_DESTROY
#define HAVE_PTHREAD_MUTEX_INIT
#define HAVE_PTHREAD_MUTEX_T
#define HAVE_PTHREAD_SETAFFINITY_NP
#define HAVE_PTHREAD_SETSCHEDPARAM
#define HAVE_PTHREAD_SIGQUEUE
#define HAVE_PTRACE
#define HAVE_PTRACE_REQUEST
#define HAVE_PTSNAME
#define HAVE_PWRITE
#define HAVE_PWRITEV
#define HAVE_PWRITEV2
#define HAVE_READLINKAT
#define HAVE_RECVMMSG
#define HAVE_REMAP_FILE_PAGES
#define HAVE_REMOVEXATTR
#define HAVE_RENAMEAT
#define HAVE_RENAMEAT2
#define HAVE_RINTL
#define HAVE_RLIMIT_RESOURCE_T
#define HAVE_RTC_PARAM
#define HAVE_RUSAGE_RU_MAXRSS
#define HAVE_RUSAGE_RU_MINFLT
#define HAVE_RUSAGE_RU_NVCSW
#define HAVE_RUSAGE_WHO_T
#define HAVE_SBRK
#define HAVE_SCHED_GETAFFINITY
#define HAVE_SCHED_GETCPU
#define HAVE_SCHED_GET_PRIORITY_MAX
#define HAVE_SCHED_GET_PRIORITY_MIN
#define HAVE_SCHED_RR_GET_INTERVAL
#define HAVE_SCHED_SETAFFINITY
#define HAVE_SCHED_SETSCHEDULER
#define HAVE_SCHED_YIELD
#define HAVE_SCSI_SCSI_H
#define HAVE_SCSI_SCSI_IOCTL_H
#define HAVE_SCSI_SG_H
#define HAVE_SEARCH_H
#define HAVE_SECCOMP_NOTIF_SIZES
#define HAVE_SELECT
#define HAVE_SEMAPHORE_H
#define HAVE_SEMTIMEDOP
#define HAVE_SEM_POSIX
#define HAVE_SEM_SYSV
#define HAVE_SENDFILE
#define HAVE_SENDMMSG
#define HAVE_SERIAL_ICOUNTER
#define HAVE_SERIAL_STRUCT
#define HAVE_SETDOMAINNAME
#define HAVE_SETFSGID
#define HAVE_SETFSUID
#define HAVE_SETITIMER
#define HAVE_SETMNTENT
#define HAVE_SETNS
#define HAVE_SETPGID
#define HAVE_SETPGRP
#define HAVE_SETPRIORITY
#define HAVE_SETPWENT
#define HAVE_SETREGID
#define HAVE_SETRESGID
#define HAVE_SETRESUID
#define HAVE_SETREUID
#define HAVE_SETTIMEOFDAY
#define HAVE_SETXATTR
#define HAVE_SHMID_DS
#define HAVE_SHMINFO
#define HAVE_SHM_SYSV
#define HAVE_SIGALTSTACK
#define HAVE_SIGNALFD
#define HAVE_SIGQUEUE
#define HAVE_SIGWAITINFO
#define HAVE_SINCOS
#define HAVE_SINCOSF
#define HAVE_SINCOSL
#define HAVE_SINHL
#define HAVE_SINL
#define HAVE_SND_CTL_CARD_INFO
#define HAVE_SND_CTL_TLV
#define HAVE_SOCKADDR_UN
#define HAVE_SOUND_ASOUND_H
#define HAVE_SPAWN_H
#define HAVE_SPLICE
#define HAVE_SQRTL
#define HAVE_SRAND48
#define HAVE_STAT
#define HAVE_STATFS
#define HAVE_STATX
#define HAVE_STRINGS_H
#define HAVE_SWAP
#define HAVE_SWAPCONTEXT
#define HAVE_SYMLINKAT
#define HAVE_SYNCFS
#define HAVE_SYNC_BOOL_COMPARE_AND_SWAP
#define HAVE_SYNC_FILE_RANGE
#define HAVE_SYNC_SYNCHRONIZE
#define HAVE_SYSCALL
#define HAVE_SYSCALL_H
#define HAVE_SYSINFO
#define HAVE_SYSLOG_H
#define HAVE_SYS_AUXV_H
#define HAVE_SYS_EPOLL_H
#define HAVE_SYS_EVENTFD_H
#define HAVE_SYS_FANOTIFY_H
#define HAVE_SYS_FSUID_H
#define HAVE_SYS_INOTIFY_H
#define HAVE_SYS_IO_H
#define HAVE_SYS_IPC_H
#define HAVE_SYS_MOUNT_H
#define HAVE_SYS_MSG_H
#define HAVE_SYS_PARAM_H
#define HAVE_SYS_PERSONALITY_H
#define HAVE_SYS_PIDFD_H
#define HAVE_SYS_PRCTL_H
#define HAVE_SYS_QUEUE_H
#define HAVE_SYS_QUOTA_H
#define HAVE_SYS_RANDOM_H
#define HAVE_SYS_SELECT_H
#define HAVE_SYS_SENDFILE_H
#define HAVE_SYS_SHM_H
#define HAVE_SYS_SIGNALFD_H
#define HAVE_SYS_STATFS_H
#define HAVE_SYS_STATVFS_H
#define HAVE_SYS_SWAP_H
#define HAVE_SYS_SYSINFO_H
#define HAVE_SYS_SYSMACROS_H
#define HAVE_SYS_TIMERFD_H
#define HAVE_SYS_TIMEX_H
#define HAVE_SYS_UIO_H
#define HAVE_SYS_UN_H
#define HAVE_SYS_UTSNAME_H
#define HAVE_SYS_VFS_H
#define HAVE_SYS_XATTR_H
#define HAVE_TARGET_CLONES
#define HAVE_TARGET_CLONES_ALDERLAKE
#define HAVE_TARGET_CLONES_AVX
#define HAVE_TARGET_CLONES_AVX2
#define HAVE_TARGET_CLONES_COOPERLAKE
#define HAVE_TARGET_CLONES_GRANITERAPIDS
#define HAVE_TARGET_CLONES_MMX
#define HAVE_TARGET_CLONES_POWER9
#define HAVE_TARGET_CLONES_ROCKETLAKE
#define HAVE_TARGET_CLONES_SAPPHIRERAPIDS
#define HAVE_TARGET_CLONES_SKYLAKE_AVX512
#define HAVE_TARGET_CLONES_SSE
#define HAVE_TARGET_CLONES_SSE2
#define HAVE_TARGET_CLONES_SSE3
#define HAVE_TARGET_CLONES_SSE4_1
#define HAVE_TARGET_CLONES_SSE4_2
#define HAVE_TARGET_CLONES_SSSE3
#define HAVE_TARGET_CLONES_TIGERLAKE
#define HAVE_TCDRAIN
#define HAVE_TCFLOW
#define HAVE_TCFLUSH
#define HAVE_TCGETATTR
#define HAVE_TEE
#define HAVE_TERMIOS
#define HAVE_TERMIOS_H
#define HAVE_TERMIO_H
#define HAVE_TGKILL_LIBC
#define HAVE_TIME
#define HAVE_TIMERFD_CREATE
#define HAVE_TIMERFD_GETTIME
#define HAVE_TIMERFD_SETTIME
#define HAVE_TIMER_CREATE
#define HAVE_TIMER_DELETE
#define HAVE_TIMER_GETOVERRUN
#define HAVE_TIMER_GETTIME
#define HAVE_TIMER_SETTIME
#define HAVE_TIMEX
#define HAVE_TPACKET_REQ3
#define HAVE_TSEARCH
#define HAVE_TTYNAME
#define HAVE_UCONTEXT_H
#define HAVE_UMOUNT2
#define HAVE_UNAME
#define HAVE_UNIMAPDESC
#define HAVE_UNLINKAT
#define HAVE_UNSHARE
#define HAVE_USBDEVFS_GETDRIVER
#define HAVE_USER_DESC
#define HAVE_UTIMBUF
#define HAVE_UTIME
#define HAVE_UTIMENSAT
#define HAVE_UTIME_H
#define HAVE_V2DI
#define HAVE_V4L2_AUDIO
#define HAVE_V4L2_AUDIOOUT
#define HAVE_V4L2_CAPABILITY
#define HAVE_V4L2_DV_TIMINGS
#define HAVE_V4L2_ENC_IDX
#define HAVE_V4L2_FRAMEBUFFER
#define HAVE_V4L2_JPEGCOMPRESSION
#define HAVE_V4L2_STD_ID
#define HAVE_VALLOC
#define HAVE_VECMATH
#define HAVE_VFORK
#define HAVE_VHANGUP
#define HAVE_VLA_ARG
#define HAVE_VMSPLICE
#define HAVE_VT_CONSIZE
#define HAVE_VT_MODE
#define HAVE_VT_SIZES
#define HAVE_VT_STAT
#define HAVE_WAIT3
#define HAVE_WAIT4
#define HAVE_WAITID
#define HAVE_WAITPID
#define HAVE_WCHAR
#define HAVE_WINSIZE
#define HAVE_X86INTRIN_H
#define HAVE_XMMINTRIN_H
#define HAVE___RESTRICT
#define HAVE__float128
#define HAVE__float80
/* #define HAVE_ACL_LIBACL_H */
/* #define HAVE_AIO_CANCEL */
/* #define HAVE_AIO_FSYNC */
/* #define HAVE_AIO_READ */
/* #define HAVE_AIO_WRITE */
/* #define HAVE_APPARMOR */
/* #define HAVE_ASM_ALPHA_DRAINA */
/* #define HAVE_ASM_ALPHA_HALT */
/* #define HAVE_ASM_ARM_TLBI */
/* #define HAVE_ASM_ARM_YIELD */
/* #define HAVE_ASM_CACHECTL_H */
/* #define HAVE_ASM_HPPA_DIAG */
/* #define HAVE_ASM_HPPA_RFI */
/* #define HAVE_ASM_M68K_EORI_SR */
/* #define HAVE_ASM_MIPS_WAIT */
/* #define HAVE_ASM_PPC64_DARN */
/* #define HAVE_ASM_PPC64_DCBST */
/* #define HAVE_ASM_PPC64_DCBT */
/* #define HAVE_ASM_PPC64_DCBTST */
/* #define HAVE_ASM_PPC64_ICBI */
/* #define HAVE_ASM_PPC64_MSYNC */
/* #define HAVE_ASM_PPC64_TLBIE */
/* #define HAVE_ASM_RISCV_FENCE */
/* #define HAVE_ASM_RISCV_FENCE_I */
/* #define HAVE_ASM_RISCV_SFENCE_VMA */
/* #define HAVE_ASM_S390_PTLB */
/* #define HAVE_ASM_SH4_RTE */
/* #define HAVE_ASM_SH4_SLEEP */
/* #define HAVE_ASM_SPARC_MEMBAR */
/* #define HAVE_ASM_SPARC_RDPR */
/* #define HAVE_ASM_SPARC_TICK */
/* #define HAVE_ATTR_XATTR_H */
/* #define HAVE_BSD_STDLIB_H */
/* #define HAVE_BSD_STRING_H */
/* #define HAVE_BSD_STRLCAT */
/* #define HAVE_BSD_STRLCPY */
/* #define HAVE_BSD_SYS_TREE_H */
/* #define HAVE_BSD_UNISTD_H */
/* #define HAVE_BSD_WCHAR */
/* #define HAVE_BUILTIN_BITREVERSE */
/* #define HAVE_BUILTIN_CPU_IS_POWER9 */
/* #define HAVE_BUILTIN_NONTEMPORAL_LOAD */
/* #define HAVE_BUILTIN_NONTEMPORAL_STORE */
/* #define HAVE_BUILTIN_ROTATELEFT16 */
/* #define HAVE_BUILTIN_ROTATELEFT32 */
/* #define HAVE_BUILTIN_ROTATELEFT64 */
/* #define HAVE_BUILTIN_ROTATELEFT8 */
/* #define HAVE_BUILTIN_ROTATERIGHT16 */
/* #define HAVE_BUILTIN_ROTATERIGHT32 */
/* #define HAVE_BUILTIN_ROTATERIGHT64 */
/* #define HAVE_BUILTIN_ROTATERIGHT8 */
/* #define HAVE_CACHEFLUSH */
/* #define HAVE_DELETE_MODULE */
/* #define HAVE_DUP3 */
/* #define HAVE_EGL_EXT_H */
/* #define HAVE_EGL_H */
/* #define HAVE_EIGEN */
/* #define HAVE_FACCESSAT2 */
/* #define HAVE_FCHMODAT2 */
/* #define HAVE_FINIT_MODULE */
/* #define HAVE_Float128x */
/* #define HAVE_Float16x */
/* #define HAVE_Float80 */
/* #define HAVE_Float80x */
/* #define HAVE_GBM_H */
/* #define HAVE_GETEXECNAME */
/* #define HAVE_GETMNTINFO */
/* #define HAVE_GLES2_H */
/* #define HAVE_INDEX */
/* #define HAVE_INTEL_IPSEC_MB_H */
/* #define HAVE_JUDY_H */
/* #define HAVE_KEYUTILS_H */
/* #define HAVE_LIBAIO_H */
/* #define HAVE_LIBKMOD_H */
/* #define HAVE_LIB_ACL */
/* #define HAVE_LIB_AIO */
/* #define HAVE_LIB_BSD */
/* #define HAVE_LIB_EGL */
/* #define HAVE_LIB_GBM */
/* #define HAVE_LIB_GLES2 */
/* #define HAVE_LIB_IPSEC_MB */
/* #define HAVE_LIB_JUDY */
/* #define HAVE_LIB_KMOD */
/* #define HAVE_LIB_MD */
/* #define HAVE_LIB_MPFR */
/* #define HAVE_LIB_SCTP */
/* #define HAVE_LIB_XXHASH */
/* #define HAVE_MACH_MACHINE_H */
/* #define HAVE_MACH_MACH_H */
/* #define HAVE_MACH_VM_STATISTICS_H */
/* #define HAVE_MEMBARRIER */
/* #define HAVE_MM_STREAM_SI128 */
/* #define HAVE_MM_STREAM_SI32 */
/* #define HAVE_MM_STREAM_SI64 */
/* #define HAVE_MPFR_H */
/* #define HAVE_MQUERY */
/* #define HAVE_NETINET_SCTP_H */
/* #define HAVE_OPEN_HOW */
/* #define HAVE_PPC_GET_TIMEBASE */
/* #define HAVE_PRAGMA_NO_HARD_DFP */
/* #define HAVE_PTHREAD_NP_H */
/* #define HAVE_QUOTACTL_FD */
/* #define HAVE_RFORK */
/* #define HAVE_RINDEX */
/* #define HAVE_SCTP_ASSOCIATION */
/* #define HAVE_SCTP_ASSOCPARAMS */
/* #define HAVE_SCTP_ASSOC_STATS */
/* #define HAVE_SCTP_ASSOC_VALUE */
/* #define HAVE_SCTP_DEFAULT_PRINFO */
/* #define HAVE_SCTP_EVENT_SUBSCRIBE */
/* #define HAVE_SCTP_GETADDRS */
/* #define HAVE_SCTP_INITMSG */
/* #define HAVE_SCTP_PADDRINFO */
/* #define HAVE_SCTP_PADDRPARAMS */
/* #define HAVE_SCTP_PRIM */
/* #define HAVE_SCTP_PROBEINTERVAL */
/* #define HAVE_SCTP_RTOINFO */
/* #define HAVE_SCTP_SCHED_TYPE */
/* #define HAVE_SCTP_SETADAPTION */
/* #define HAVE_SCTP_STATUS */
/* #define HAVE_SCTP_STREAM_VALUE */
/* #define HAVE_SETPROCTITLE */
/* #define HAVE_STIME */
/* #define HAVE_SYS_ACL_H */
/* #define HAVE_SYS_APPARMOR_H */
/* #define HAVE_SYS_CAPABILITY_H */
/* #define HAVE_SYS_LOADAVG_H */
/* #define HAVE_SYS_PLATFORM_PPC_H */
/* #define HAVE_SYS_SYSCTL_H */
/* #define HAVE_SYS_TREE_H */
/* #define HAVE_SYS_UCRED_H */
/* #define HAVE_SYS_VMMETER_H */
/* #define HAVE_USTAT */
/* #define HAVE_USTAT_H */
/* #define HAVE_UVM_UVM_EXTERN_H */
/* #define HAVE_WCSCASECMP */
/* #define HAVE_WCSCAT */
/* #define HAVE_WCSCHR */
/* #define HAVE_WCSCMP */
/* #define HAVE_WCSCOLL */
/* #define HAVE_WCSCPY */
/* #define HAVE_WCSLCAT */
/* #define HAVE_WCSLCPY */
/* #define HAVE_WCSLEN */
/* #define HAVE_WCSNCASECMP */
/* #define HAVE_WCSNCAT */
/* #define HAVE_WCSNCMP */
/* #define HAVE_WCSRCHR */
/* #define HAVE_WCSXFRM */
/* #define HAVE_XXHASH_H */
/* #define HAVE_fp16 */
